document.writeln("<div class=\'footer\'>");
document.writeln("        <div class=\'item\'>");
document.writeln("            <a href=\'index.html\'>");
document.writeln("                <div class=\'img\'></div>");
document.writeln("                <span>首页</span>");
document.writeln("            </a>");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'item\'>");
document.writeln("            <a href=\'class.html\'>");
document.writeln("                <div class=\'img\'></div>");
document.writeln("                <span>分类</span>");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'item\'>");
document.writeln("            <a href=\'find.html\'>");
document.writeln("                <div class=\'img\'></div>");
document.writeln("                <span>发现</span>");
document.writeln("            </a>");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'item\'>");
document.writeln("            <a href=\'myself.html\'>");
document.writeln("                <div class=\'img\'></div>");
document.writeln("                <span>我的</span>");
document.writeln("            </a>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");