document.writeln("<!-- 头部 -->");
document.writeln("    <div class=\'header\'>");
document.writeln("        <div class=\'bgcolor\'>");
document.writeln("            <nav class=\'nav clearfix\'>");
document.writeln("                <div class=\'pull-left log\'>");
document.writeln("                    <img src=\'images/BeeLog.png\' alt=\'\'>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'pull-left search\'>");
document.writeln("                    <img class=\'searchlog\' src=\'images/Head_Log2.png\' alt=\'\'>");
document.writeln("                    <input type=\'text\' placeholder=\'输入商家、分类或商圈\' onfocus=\"skip()\" id=\'searchinput\'>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'pull-left log2\'>");
document.writeln("                    <img src=\'images/Head_Log3.png\' alt=\'\'>");
document.writeln("                </div>");
document.writeln("                <div class=\'pull-left log3\'>");
document.writeln("                    <img src=\'images/Head_Log4.png\' alt=\'\'>");
document.writeln("                </div>");
document.writeln("");
document.writeln("            </nav>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");