document.writeln("<div class=\'footer\'>");
document.writeln("        <div class=\'top\'>");
document.writeln("            <div class=\'uls\'>");
document.writeln("                <ul>");
document.writeln("                    <li>005 7357 5752 1754</li>");
document.writeln("                    <li>11166248@qq.com</li>");
document.writeln("                    <li>深圳市龙岗区中心城</li>");
document.writeln("                    <li class=\'imglst\'>");
document.writeln("                        <a href=\'\' class=\'img\'>");
document.writeln("                            <img src=\'./images/footer_linklog1.png\' alt=\'\'>");
document.writeln("                        </a href=\'\'>");
document.writeln("                        <a href=\'\' class=\'img\'>");
document.writeln("                            <img src=\'./images/footer_linklog2.png\' alt=\'\'>");
document.writeln("                        </a href=\'\'>");
document.writeln("                        <a href=\'\' class=\'img\'>");
document.writeln("                            <img src=\'./images/footer_linklog3.png\' alt=\'\'>");
document.writeln("                        </a href=\'\'>");
document.writeln("                        <a href=\'\' class=\'img\'>");
document.writeln("                            <img src=\'./images/footer_linklog4.png\' alt=\'\'>");
document.writeln("                        </a href=\'\'>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>学校概况</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>校长致辞</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>学校沿革</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>历任领导</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>现任领导</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>教育教学</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>本生教育</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>研生教育</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>留生教育</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>继续教育</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>招生就业</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>本科生招</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>研究生招</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>留学生招</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>学生职业</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'bottom\'>");
document.writeln("            <p>版权所有 粤ICP备14024232号-3 </p>");
document.writeln("        </div>");
document.writeln("    </div>");