document.writeln(" <div class=\'head\'>");
document.writeln("        <div class=\'bgcolor\'>");
document.writeln("");
document.writeln("            <div id=\'carousel-example-generic\' class=\'carousel_bigimg carousel slide\' data-ride=\'carousel\'>");
document.writeln("                <div class=\'head_navbar\'>");
document.writeln("                    <div class=\'container\'>");
document.writeln("                            <div class=\' log fl\'>");
document.writeln("                                <div class=\'img fl \'>");
document.writeln("                                    <img src=\'images/index_head_log.png\' alt=\'\'>");
document.writeln("                                </div>");
document.writeln("                                <div class=\'head_log_word fl\'>");
document.writeln("                                    <h3>广州天河金领技工学校</h3>");
document.writeln("                                    <span>继续教育培训中心</span>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <label for=\'navsmall\' class=\'navsmalllabel glyphicon glyphicon-list\'>");
document.writeln("                               ");
document.writeln("                            </label>");
document.writeln("                            <div class=\'navbtn fr\'>");
document.writeln("                                <a href=\'index.html\'>网站首页</a>");
document.writeln("");
document.writeln("");
document.writeln("                                <a href=\'Department.html\'>部门简介</a>");
document.writeln("");
document.writeln("");
document.writeln("                                <a href=\'index.html\'>学历教育</a>");
document.writeln("");
document.writeln("");
document.writeln("                                <a href=\'index.html\'>技能考证培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                                <a href=\'index.html\'>职业资格培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                                <a href=\'index.html\'>创业培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                                <a href=\'index.html\'>特色培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                                <a href=\'index.html\'>企业定制培训</a>");
document.writeln("");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <input type=\'checkbox\' id=\'navsmall\'>");
document.writeln("                <div class=\'navbtnsmall\'>");
document.writeln("                    <a href=\'index.html\'>网站首页</a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'Department.html\'>部门简介</a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'index.html\'>学历教育</a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'index.html\'>技能考证培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'index.html\'>职业资格培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'index.html\'>创业培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'index.html\'>特色培训</a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'index.html\'>企业定制培训</a>");
document.writeln("");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <!-- Indicators -->");
document.writeln("                <ol class=\'carousel-indicators\'>");
document.writeln("                    <li data-target=\'#carousel-example-generic\' data-slide-to=\'0\' class=\'active\'></li>");
document.writeln("                    <li data-target=\'#carousel-example-generic\' data-slide-to=\'1\'></li>");
document.writeln("                    <li data-target=\'#carousel-example-generic\' data-slide-to=\'2\'></li>");
document.writeln("                </ol>");
document.writeln("");
document.writeln("                <!-- Wrapper for slides -->");
document.writeln("                <div class=\'carousel-inner\' role=\'listbox\'>");
document.writeln("                    <div class=\'item active\'>");
document.writeln("                        <img class=\'img-responsive\' src=\'images/index_head_bigbg.png\' alt=\'...\'>");
document.writeln("                        <div class=\'carousel-caption\'>");
document.writeln("                            <div class=\'head_carousel_caption_box\'>");
document.writeln("                                <p>");
document.writeln("                                    有另一种语言");
document.writeln("                                </p>");
document.writeln("                                <p>是拥有第二个灵魂</p>");
document.writeln("                                <span>");
document.writeln("                                    There is another language , Is to have second souls");
document.writeln("                                </span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'item \'>");
document.writeln("                        <img class=\'img-responsive\' src=\'images/index_head_bigbg.png\' alt=\'...\'>");
document.writeln("                        <div class=\'carousel-caption\'>");
document.writeln("                            <div class=\'head_carousel_caption_box\'>");
document.writeln("                                <p>");
document.writeln("                                    有另一种语言");
document.writeln("                                </p>");
document.writeln("                                <p>是拥有第二个灵魂</p>");
document.writeln("                                <span>");
document.writeln("                                    There is another language , Is to have second souls");
document.writeln("                                </span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'item \'>");
document.writeln("                        <img class=\'img-responsive\' src=\'images/index_head_bigbg.png\' alt=\'...\'>");
document.writeln("                        <div class=\'carousel-caption\'>");
document.writeln("                            <div class=\'head_carousel_caption_box\'>");
document.writeln("                                <p>");
document.writeln("                                    有另一种语言");
document.writeln("                                </p>");
document.writeln("                                <p>是拥有第二个灵魂</p>");
document.writeln("                                <span>");
document.writeln("                                    There is another language , Is to have second souls");
document.writeln("                                </span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <!-- Controls -->");
document.writeln("                <a class=\'left carousel-control\' href=\'#carousel-example-generic\' role=\'button\' data-slide=\'prev\'>");
document.writeln("                    <span class=\'glyphicon glyphicon-chevron-left\' aria-hidden=\'true\'></span>");
document.writeln("                    <span class=\'sr-only\'>Previous</span>");
document.writeln("                </a>");
document.writeln("                <a class=\'right carousel-control\' href=\'#carousel-example-generic\' role=\'button\' data-slide=\'next\'>");
document.writeln("                    <span class=\'glyphicon glyphicon-chevron-right\' aria-hidden=\'true\'></span>");
document.writeln("                    <span class=\'sr-only\'>Next</span>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");