document.writeln("<!-- 页尾 -->");
document.writeln("    <footer class=\'footer\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'flex\'>");
document.writeln("                <input type=\'radio\' name=\'footerbtn\' id=\'footerbtn1\'>");
document.writeln("                <label for=\'footerbtn1\'>");
document.writeln("                    <a href=\'index.html\'>");
document.writeln("                        <div class=\'item\'>");
document.writeln("");
document.writeln("                            <div class=\'img\'>");
document.writeln("");
document.writeln("                                <img src=\'images/Footer_Log1.png\' alt=\'\'>");
document.writeln("                                <img src=\'images/Footer_Log1Hover.png\' alt=\'\'>");
document.writeln("                            </div>");
document.writeln("                            <span>首页</span>");
document.writeln("");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </label>");
document.writeln("                <input type=\'radio\' name=\'footerbtn\' id=\'footerbtn2\'>");
document.writeln("                <label for=\'footerbtn2\'>");
document.writeln("                    <a href=\'classify.html\'>");
document.writeln("                        <div class=\'item\'>");
document.writeln("                            <div class=\'img\'>");
document.writeln("                                <img src=\'images/Footer_Log2.png\' alt=\'\'>");
document.writeln("                                <img src=\'images/Footer_Log2Hover.png\' alt=\'\'>");
document.writeln("                            </div>");
document.writeln("                            <span>闪送超市</span>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </label>");
document.writeln("                <input type=\'radio\' name=\'footerbtn\' id=\'footerbtn3\'>");
document.writeln("                <label for=\'footerbtn3\'>");
document.writeln("                    <a href=\'personal.html\'>");
document.writeln("                        <div class=\'item\'>");
document.writeln("                            <div class=\'img\'>");
document.writeln("                                <img src=\'images/Footer_Log3.png\' alt=\'\'>");
document.writeln("                                <img src=\'images/Footer_Log3Hover.png\' alt=\'\'>");
document.writeln("                            </div>");
document.writeln("                            <span>我的</span>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </label>");
document.writeln("                <input type=\'radio\' name=\'footerbtn\' id=\'footerbtn4\'>");
document.writeln("                <label for=\'footerbtn4\'>");
document.writeln("                    <a href=\'productDetail.html\'>");
document.writeln("                        <div class=\'item\'>");
document.writeln("                            <div class=\'img\'>");
document.writeln("                                <img src=\'images/Footer_Log4.png\' alt=\'\'>");
document.writeln("                                <img src=\'images/Footer_Log4Hover.png\' alt=\'\'>");
document.writeln("                            </div>");
document.writeln("                            <span>¥0起送</span>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </label>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </footer>");