document.writeln("<!-- 页尾 -->");
document.writeln("<div class=\'footer\'>");
document.writeln("    <div class=\'followus\'>");
document.writeln("        <span>关注我们 :</span>");
document.writeln("        <a href=\'\'>");
document.writeln("            <img src=\'images/followus1.png\' alt=\'\'>");
document.writeln("        </a>");
document.writeln("        <a href=\'\'>");
document.writeln("            <img src=\'images/followus2.png\' alt=\'\'>");
document.writeln("        </a>");
document.writeln("        <a href=\'\'>");
document.writeln("            <img src=\'images/followus3.png\' alt=\'\'>");
document.writeln("        </a>");
document.writeln("    </div>");
document.writeln("    <div class=\'nav\'>");
document.writeln("        <a href=\'\'>网站首页</a>");
document.writeln("        <a href=\'\'>新闻动态</a>");
document.writeln("        <a href=\'\'>关于我们</a>");
document.writeln("        <a href=\'\'>团队风采</a>");
document.writeln("        <a href=\'\'>联系我们</a>");
document.writeln("        <a href=\'\'>在线留言</a>");
document.writeln("    </div>");
document.writeln("    <div class=\'register\'>");
document.writeln("        ©2015 TK科技有限公司 版权所有沪ICP证13022560号-7 All Rights Reserved");
document.writeln("    </div>");
document.writeln("</div>");