document.writeln("<div class=\'page\'>");
document.writeln("      <!-- 网页头部 -->");
document.writeln("      <input type=\'checkbox\' name=\'\' value=\'\' id=\'nav_flex1\' hidden>");
document.writeln("      <div class=\'header\'>");
document.writeln("        <div class=\'tagsbgcolor\'>");
document.writeln("          <div class=\'center\'>");
document.writeln("                <div class=\'tags\'>");
document.writeln("                  <div class=\'tags_left\'>");
document.writeln("                    <a>全国服务热线：400-000-0000</a>");
document.writeln("                  </div>");
document.writeln("                  <div class=\'tags_right\'>");
document.writeln("                    <a href=\'#\'>设为首页</a>");
document.writeln("                    <a href=\'#\'>加入收藏</a>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'navbgcolor\'>");
document.writeln("          <div class=\'center\'>");
document.writeln("            <div class=\'nav\'>");
document.writeln("              <div class=\'nav_left\'>");
document.writeln("                <div class=\'img\'>");
document.writeln("                  <img src=\'images/header_navleftimg.png\' alt=\'\'>");
document.writeln("                </div>");
document.writeln("                <div class=\'text\'>");
document.writeln("                  <h3>TK科技有限公司</h3>");
document.writeln("                  <span>cer dcd keo Holdings Co., Ltd.</span>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("");
document.writeln("              <div class=\'nav_right\'>");
document.writeln("                  <a href=\'index.html\'>首页<p>Home</p> <div class=\'shade\'></div> </a>");
document.writeln("                  <a href=\'#\'>关于我们<p>About</p> <div class=\'shade\'></div> </a>");
document.writeln("                  <a href=\'product.html\'>产品中心<p>Products</p> <div class=\'shade\'></div> </a>");
document.writeln("                  <a href=\'#\'>服务支持<p>Service</p> <div class=\'shade\'></div> </a>");
document.writeln("                  <a href=\'#\'>新闻中心<p>News</p> <div class=\'shade\'></div> </a>");
document.writeln("                  <a href=\'#\'>在线商店<p>Contact</p> <div class=\'shade\'></div> </a>");
document.writeln("                  <a href=\'#\'>联系我们<p>Contact Us</p> <div class=\'shade\'></div> </a>");
document.writeln("              </div>");
document.writeln("");
document.writeln("              <label for=\'nav_flex1\' class=\'nav_flex\'>");
document.writeln("                <span></span>");
document.writeln("                <span></span>");
document.writeln("                <span></span>");
document.writeln("              </label>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <div class=\'nav_flex_hidden\'>");
document.writeln("        <div>");
document.writeln("          <a href=\'index.html\'>首页<p>Home</p> <div class=\'shade\'></div> </a>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("          <a href=\'#\'>关于我们<p>About</p> <div class=\'shade\'></div> </a>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("          <a href=\'product.html\'>产品中心<p>Products</p> <div class=\'shade\'></div> </a>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("          <a href=\'#\'>服务支持<p>Service</p> <div class=\'shade\'></div> </a>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("          <a href=\'#\'>新闻中心<p>News</p> <div class=\'shade\'></div> </a>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("          <a href=\'#\'>在线商店<p>Contact</p> <div class=\'shade\'></div> </a>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("          <a href=\'#\'>联系我们<p>Contact Us</p> <div class=\'shade\'></div> </a>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
