document.writeln("<div class=\'footer\'>");
document.writeln("        <div class=\'footer_bgcolor\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'footer_box clearf\'>");
document.writeln("                    <div class=\'footer_log\'>");
document.writeln("                        <div class=\'img\'>");
document.writeln("                            <img src=\'./images/footer_log.png\' alt=\'\'>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'line\'></div>");
document.writeln("                    <div class=\'footer_nav\'>");
document.writeln("");
document.writeln("                        <div class=\'w12\'>");
document.writeln("                            <h3>导航 NAVIGATION</h3>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'w6\'>");
document.writeln("                            <a href=\'index.html\'>网站首页</a>");
document.writeln("");
document.writeln("                        </div>");
document.writeln("");
document.writeln("                        <div class=\'w6\'>");
document.writeln("                            <a href=\'brand.html\'>走进尚典</a>");
document.writeln("                        </div>");
document.writeln("");
document.writeln("                        <div class=\'w6\'>");
document.writeln("                            <a href=\'news.html\'>新闻动态</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'w6\'>");
document.writeln("                            <a href=\'video.html\'>尚典视频</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'w6\'>");
document.writeln("                            <a href=\'product.html\'>产品中心</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'w6\'>");
document.writeln("                            <a href=\'select.html\'>授权查询</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'w6\'>");
document.writeln("                            <a href=\'contact.html\'>联系我们</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                    <div class=\'line\'></div>");
document.writeln("                    <div class=\'footer_contact\'>");
document.writeln("");
document.writeln("                        <h3>联系 CONTACT</h3>");
document.writeln("");
document.writeln("                        <div class=\'w12\'>");
document.writeln("                            <span>地址：广州市海珠区赤岗街道新市头路锦安苑锦豪居C栋502</span>");
document.writeln("                        </div>");
document.writeln("");
document.writeln("                        <div class=\'w12\'>");
document.writeln("                            <span>联系电话：400-1886-1345</span>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'w12\'>");
document.writeln("                            <span>邮箱：203841290@qq.com</span>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'w12\'>");
document.writeln("                            <span>香港闻名生物有限公司版权所有 粤ICP备0754673</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'line\'></div>");
document.writeln("                    <div class=\'footer_QRcode\'>");
document.writeln("                        <div class=\'img\'>");
document.writeln("                            <img src=\'./images/footer_QRcode.png\' alt=\'\'>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");