document.writeln("<div class=\'header\' id=\'header\'>");
document.writeln("        <div class=\'header_bgcolor\'>");
document.writeln("            <input type=\'checkbox\' id=\'media_navlist\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("");
document.writeln("                <!-- 整个导航条 -->");
document.writeln("                <div class=\'header_nav clearf\'>");
document.writeln("                    <div class=\'header_log fl\'>");
document.writeln("                        <div class=\'img\'>");
document.writeln("                            <img src=\'./images/header_log.png\' alt=\'\'>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <!-- 导航列 -->");
document.writeln("                    <div class=\'header_list fr clearf \'>");
document.writeln("                        <a href=\'index.html\'>首页</a>");
document.writeln("                        <a href=\'brand.html\'>走进尚典 </a>");
document.writeln("                        <a href=\'news.html\'>新闻动态 </a>");
document.writeln("                        <a href=\'video.html\'>尚典视频 </a>");
document.writeln("                        <a href=\'product.html\'>产品中心 </a>");
document.writeln("                        <a href=\'select.html\'>授权查询 </a>");
document.writeln("                        <a href=\'contact.html\'>联系我们 </a>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    <!-- 导航按钮 -->");
document.writeln("");
document.writeln("                    <div class=\'header_menu_btn\'>");
document.writeln("                        <label for=\'media_navlist\'>");
document.writeln("                            <span></span>");
document.writeln("                            <span></span>");
document.writeln("                            <span></span>");
document.writeln("                        </label>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("");
document.writeln("                </div>");
document.writeln("");
document.writeln("            </div>");
document.writeln(" <!-- 响应式模式下的导航列 -->");
document.writeln("            <div class=\'header_media_list clearf \'>");
document.writeln("                        <a href=\'index.html\'>首页</a>");
document.writeln("                        <a href=\'brand.html\'>走进尚典 </a>");
document.writeln("                        <a href=\'news.html\'>新闻动态 </a>");
document.writeln("                        <a href=\'video.html\'>尚典视频 </a>");
document.writeln("                        <a href=\'product.html\'>产品中心 </a>");
document.writeln("                        <a href=\'select.html\'>授权查询 </a>");
document.writeln("                        <a href=\'contact.html\'>联系我们 </a>");
document.writeln("            </div>");
document.writeln("           ");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");